---
abstract: 'Update a static website'
author:
  - 'Bernie Simon <bernie.simon@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Followme
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  App::Followme:
    file: lib/App/Followme.pm
    version: 1.00
  App::Followme::ConvertPage:
    file: lib/App/Followme/ConvertPage.pm
    version: 1.00
  App::Followme::CreateIndex:
    file: lib/App/Followme/CreateIndex.pm
    version: 1.00
  App::Followme::CreateNews:
    file: lib/App/Followme/CreateNews.pm
    version: 1.00
  App::Followme::EveryFile:
    file: lib/App/Followme/EveryFile.pm
    version: 1.00
  App::Followme::FormatPage:
    file: lib/App/Followme/FormatPage.pm
    version: 1.00
  App::Followme::HandleSite:
    file: lib/App/Followme/HandleSite.pm
    version: 1.00
  App::Followme::Initialize:
    file: lib/App/Followme/Initialize.pm
    version: 1.00
  App::Followme::Mock:
    file: lib/App/Followme/Mock.pm
    version: 1.00
  App::Followme::MostRecentFile:
    file: lib/App/Followme/MostRecentFile.pm
    version: 1.00
  App::Followme::UploadFtp:
    file: lib/App/Followme/UploadFtp.pm
    version: 1.00
  App::Followme::UploadNone:
    file: lib/App/Followme/UploadNone.pm
    version: 1.00
  App::Followme::UploadSite:
    file: lib/App/Followme/UploadSite.pm
    version: 1.00
  App::Followme::Variables:
    file: lib/App/Followme/Variables.pm
    version: 1.00
requires:
  Text::Markdown: 1.000031
  perl: 5.008005
resources:
  bugtracker: https://github.com/Jinzang/App-Followme/issues
  homepage: https://github.com/Jinzang/App-Followme
  repository: https://github.com/Jinzang/App-Followme.git
version: 1.00
