---
abstract: 'Update a static website'
author:
  - 'Bernie Simon <bernie.simon@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Followme
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  App::Followme:
    file: lib/App/Followme.pm
    version: 0.91
  App::Followme::Common:
    file: lib/App/Followme/Common.pm
    version: 0.91
  App::Followme::ConvertPages:
    file: lib/App/Followme/ConvertPages.pm
    version: 0.91
  App::Followme::CreateIndexes:
    file: lib/App/Followme/CreateIndexes.pm
    version: 0.91
  App::Followme::CreateNews:
    file: lib/App/Followme/CreateNews.pm
    version: 0.91
  App::Followme::FormatPages:
    file: lib/App/Followme/FormatPages.pm
    version: 0.91
  App::Followme::Initialize:
    file: lib/App/Followme/Initialize.pm
    version: 0.91
  App::Followme::Mock:
    file: lib/App/Followme/Mock.pm
    version: 0.91
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/Jinzang/App-Followme/issues
  homepage: https://github.com/Jinzang/App-Followme
  repository: https://github.com/Jinzang/App-Followme.git
version: 0.91
